name: Upload Python Package - ezmsg-lsl

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Build Package
        run: uv build

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist

  pypi-publish:
    needs: [ "build" ]
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: "release"
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@v3

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: artifact/
